name: Autoupdate docker image

on: 
  push:
    paths:
      - "Dockerfile"
      - "package.json"
      - "pnpm-lock.yaml"

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Login to Dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN}}

      - name: Update Image
        uses: docker/build-push-action@v3
        with:
          content: .
          push: true
          tags: "marinofajardo/controlatugasto:latest"


